spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        ddl-auto: drop-and-create   # create na primeira vez e depois volte pra validate
        temp:
          use_jdbc_metadata_defaults: false


#     username: ${PGUSER}
  #    password: ${PGPASSWORD}
#  url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
  #  spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
 # spring.jpa.properties.hibernate.dialect.format_sql = true
  # connection.provider_class=com.zaxxer.hikari.hibernate.HikariConnectionProvider