spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create   # create na primeira vez e depois volte pra validate
      dialect: org.hibernate.dialect.PostgreSQLDialect


#  spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
 # spring.jpa.properties.hibernate.dialect.format_sql = true